sao_arena/arena/urls.py
from django.conf.urls import include, url, patterns
from django.conf import settings

from .api import *

urlpatterns = [
    url(r'^actions/$', ActionViewList.as_view(), name='action-list'),
    url(r'^actions/(?P<pk>\d+)/$', ActionViewDetail.as_view(), name='action-detail'),
    url(r'^damage-types/$', Damage_TypeViewList.as_view(), name='damage_type-list'),
    url(r'^damage-types/(?P<pk>\d+)/$', Damage_TypeViewDetail.as_view(), name='damage_type-detail'),
    url(r'^characters/$', CharacterViewList.as_view(), name='character-list'),
    url(r'^characters/(?P<pk>\d+)/$', CharacterViewDetail.as_view(), name='character-detail'),
    url(r'^effects/$', EffectViewList.as_view(), name='effect-list'),
    url(r'^effects/(?P<pk>\d+)/$', EffectViewDetail.as_view(), name='effect-detail'),
    url(r'^energy/$', EnergyViewList.as_view(), name='energy-list'),
    url(r'^energy/(?P<pk>\d+)/$', EnergyViewDetail.as_view(), name='energy-detail'),
    url(r'^missions/$', MissionViewList.as_view(), name='misssion-list'),
    url(r'^missions/(?P<pk>\d+)/$', MissionViewDetail.as_view(), name='mission-detail'),
    url(r'^objectives/$', ObjectiveViewList.as_view(), name='objective-list'),
    url(r'^objectives/(?P<pk>\d+)/$', ObjectiveViewDetail.as_view(), name='objective-detail'),
    url(r'^player-profiles/$', PlayerProfileViewList.as_view(), name='player-profile-list'),
    url(r'^player-profiles/(?P<pk>\d+)/$', PlayerProfileViewDetail.as_view(), name='player-profile-detail'),
    url(r'^skills/$', SkillViewList.as_view(), name='skill-list'),
    url(r'^skills/(?P<pk>\d+)/$', SkillViewDetail.as_view(), name='skill-detail'),
    url(r'^skill-types/$', Skill_TypeViewList.as_view(), name='skill-type-list'),
    url(r'^skill-types/(?P<pk>\d+)/$', Skill_TypeViewDetail.as_view(), name='skill-type-detail'),
    url(r'^targets/$', TargetViewList.as_view(), name='target-list'),
    url(r'^targets/(?P<pk>\d+)/$', TargetViewDetail.as_view(), name='target-detail'),
    url(r'^users/$', UserViewList.as_view(), name='user-list'),
    url(r'^users/(?P<pk>\d+/$)', UserViewDetail.as_view(), name='user-detail'),

    
]

sao_arena/game/urls.py
from django.conf.urls import include, url, patterns
from django.conf import settings

from .api import *
from .views import join_game_view, home_view

urlpatterns = [
    url(r'^active-effects/$',Active_EffectViewList.as_view(), name='active-effect-list'),
    url(r'^actions/(?P<pk>\d+)/$', Active_EffectViewDetail.as_view(), name='active-effect-detail'),
    url(r'^blocked-skills/$', Blocked_SkillViewList.as_view(), name='blocked-skill-list'),
    url(r'^blocked-skills/(?P<pk>\d+)/$', Blocked_SkillViewDetail.as_view(), name='blocked-skill-detail'),
    url(r'^character-stats/$', Character_StatsViewList.as_view(), name='character-stats-list'),
    url(r'^character-stats/(?P<pk>\d+)/$', Character_StatsViewDetail.as_view(), name='character-stats-detail'),
    url(r'^games/$', GameViewList.as_view(), name='game-list'),
    url(r'^games/(?P<pk>\d+)/$', GameViewDetail.as_view(), name='game-detail'),
    url(r'^games/by-player/(?P<pk>\d+)/$', game_by_player_id, name='game-by-player-id'),
    url(r'^players/$', PlayerViewList.as_view(), name='player-list'),
    url(r'^players/(?P<pk>\d+)/$', PlayerViewDetail.as_view(), name='player-detail'),
    
    url(r'player/update/(?P<pk>\d+)/$', in_game_details, name='player-update'),
    url(r'player/endturn/(?P<pk>\d+)/$', end_turn, name='player-end-turn'),
]

sao_arena/sao_arena/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from arena.views import home_view
from arena import views as arena_views
from django.conf import settings

from arena import urls as arena_urls
from game import urls as game_urls
from game.views import join_game_view
from game.views import home_view as game_home_view
from game.views import game_start_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/arena/', include(arena_urls)),
    url(r'^api/game/', include(game_urls)),
    url(r'^$', home_view, name="Home"),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT,}),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^game-manual/characters/$', arena_views.CharacterView, name='characters'),
    url(r'^game-manual/characters/(?P<slug>[\w-]+)$', arena_views.CharacterSkillsView, name='character skills'),
    url(r'^profile$', arena_views.PlayerProfileView, name='Profile'),
    
    url(r'^game/join/(?P<pk>\d+)/$', join_game_view, name='join-game'),
    url(r'^game/join/$', game_home_view, name='join-game-home'),
    
    url(r'^game/start/(?P<pk>\d+)/$', game_start_view, name='join-game'),
]

sao_arena/arena/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


TARGETS = (
    ('Self', 'Self'),
    ('Ally', 'Ally'),
    ('Enemy', 'Enemy'),
)

ACTION_TYPES = (
    ('inc','Increase'),
    ('red','Reduce'),
    ('prev','Prevent'),
    ('ign','Ignore'),
    ('give','Give'),
    ('cntn','Counter Next'),
    ('cnta','Counter All'),
)

ACTION_FIELDS = (
    ('inv','Invulnerability'),
    ('dmg','Damage'),
    ('dmgr','Damage Reduction'),
    ('stn','Stun'),
    ('desd','Destructable Defense'),
    ('cntn','Counter Next'),
    ('cnta','Counter All'),
)

COLORS = (
    ('Green','Green'),
    ('Red','Red'),
    ('Blue','Blue'),
    ('White','White'),
    ('Black','Black'),
)

TIME_PERIODS = (
    ('SAO','Sword Art Online'),
    ('ALO', 'Alfheim Online'),
    ('SAO2', 'New SAO'),
    ('ALO2', 'New Alfheim Online'),
    ('GGO','Gun Gale Online'),
)
    
CHARACTER_TYPES = (
    ('Player', 'Player'),
    ('NPC', 'NPC'),
    ('Monster', 'Monster'),
)

# Create your models here. 
class Action(models.Model):
    action_type             = models.CharField(max_length=50, null=False, blank=False, choices=ACTION_TYPES)
    action_field            = models.CharField(max_length=50, null=False, blank=False, choices=ACTION_FIELDS)
    amount                  = models.IntegerField(null=False, blank=False, default=0)
    affected_skilltypes     = models.ManyToManyField('Skill_Type', blank=True)
    chained_actions         = models.ManyToManyField('Action', blank=True)
    select_skill            = models.ManyToManyField('Skill', blank=True)
    slug                    = models.SlugField(unique=True)
    
    has_skilltype_requirement = models.BooleanField(blank=False, null=False, default=False)
    has_chained_action = models.BooleanField(blank=False, null=False, default=False)
    
    def __unicode__(self):
        return self.slug
    
    
class Damage_Type(models.Model):
    name                  = models.CharField(max_length=50, null=False, blank=False)
    turn_length           = models.IntegerField(null=False, blank=False, default=1)
    amount                = models.IntegerField(null=False, blank=False, default=0)
    targets                = models.ManyToManyField('Target', blank=False)
    secondary_random      = models.BooleanField(blank=False, null=False, default=False)
    slug                  = models.SlugField(unique=True)
    
    def __unicode__(self):
        return self.slug
    
class Effect(models.Model):
    name            = models.CharField(max_length=50, null=False, blank=False)
    turn_length     = models.IntegerField(null=False, blank=False, default=1)
    targets         = models.ManyToManyField('Target', blank=False)
    actions         = models.ManyToManyField('Action', blank=False)
    slug            = models.SlugField(unique=True)
    
    def __unicode__(self):
        return self.slug
    
# Create your models here.
class Energy(models.Model):
    name = models.CharField(max_length=50, unique=True, null=False, blank=False)
    color = models.CharField(max_length=20, choices=COLORS, null=False, blank=False)
    amount = models.IntegerField(blank=False, null=False, default=1)
    #description = models.TextField(max_length=300, blank=True, null=True)
    
    
    def __unicode__(self):
        
        return self.name
    
class Skill(models.Model):
    name         = models.CharField(max_length=50, null=False, blank=False)
    description  = models.TextField(max_length=300, null=False, blank=False)
    damage_types = models.ManyToManyField('Damage_Type', null=False, blank=False, related_name='damagetype_set')
    effects      = models.ManyToManyField('Effect', blank=True)
    energy       = models.ManyToManyField('Energy')
    cooldown     = models.IntegerField(null=False, blank=False, default=0)
    skill_types  = models.ManyToManyField('Skill_Type', blank=True)
    image        = models.ImageField(null=False, blank=False, upload_to='img/skills')
    linked_skill = models.ForeignKey('Skill', blank=True, null=True, related_name='linkedskill_set')
    required_skill        = models.ForeignKey('Skill', blank=True, null=True, related_name='requiredskill_set')
    position     = models.IntegerField(null=False, blank=False, default=0)
    
    def __unicode__(self):
        return self.name
    
class Skill_Type(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False)
    
    def __unicode__(self):
        return self.name
    
class Character(models.Model):
    
    name                = models.CharField(max_length=50, null=False, blank=False)
    description         = models.TextField(max_length=300, null=False, blank=False)
    image               = models.ImageField(null=False, blank=False, upload_to='img/skills')
    skills              = models.ManyToManyField('Skill')
    linked_character    = models.ForeignKey('Character', blank=True, null=True)
    character_type      = models.CharField(max_length=50, blank=True, null=True, choices=CHARACTER_TYPES)
    time_period         = models.CharField(max_length=50, blank=True, null=True, choices=TIME_PERIODS)
    activating_missions = models.ManyToManyField('Mission', blank=True)
    slug                = models.SlugField(editable=True, unique=True)
    
    def __unicode__(self):
        return self.name
    
class Objective(models.Model): 
    name           = models.CharField(max_length=50, null=False, blank=False)
    description    = models.TextField(max_length=300, null=False, blank=False)
    character      = models.ForeignKey('Character')
    character_type = models.CharField(max_length=50, blank=True, null=True, choices=CHARACTER_TYPES)
    time_period    = models.CharField(max_length=50, blank=True, null=True, choices=TIME_PERIODS)
    wins_against   = models.IntegerField(null=False, blank=False, default=1)
    wins_in_a_row  = models.IntegerField(null=False, blank=False, default=1)
    slug           = models.SlugField(editable=True, unique=False)
    completed      = models.BooleanField(editable=False, default=False) 
    
    def __unicode__(self):
        return self.name
    
class Mission(models.Model):
    name           = models.CharField(max_length=50, null=False, blank=False)
    description    = models.TextField(max_length=300, null=False, blank=False)
    objectives     = models.ManyToManyField('Objective')
    
    def __unicode__(self):
        return self.name
    
    
class PlayerProfile(models.Model):
    user = models.OneToOneField(User, null=False)
    avatar = models.ImageField(null=True, blank=True, upload_to='img/avatars')
    level = models.IntegerField(default=1, null=False)
    wins = models.IntegerField(default=0, null=False)
    defeats = models.IntegerField(default=0, null=False)
    winstreak = models.IntegerField(default=0, null=False)
    character_1 = models.ForeignKey('Character', related_name="+", null=True, blank=True)
    character_2 = models.ForeignKey('Character', related_name="+", null=True, blank=True)
    character_3 = models.ForeignKey('Character', related_name="+", null=True, blank=True)

    def get_characters(self):
        characters = []
        characters.append(self.character_1)
        characters.append(self.character_2)
        characters.append(self.character_3)
        
        return characters 

    def __unicode__(self):
        return self.user.username
    
    
class Target(models.Model):
    target_name         = models.CharField(max_length=50, null=False, blank=False, choices=TARGETS)
    amount              = models.IntegerField(null=False, blank=False, default=1)
    secondary_random    = models.BooleanField(null=False, blank=False, default=False)
    slug                = models.SlugField(unique=True)

    def __unicode__(self):
        return self.slug

def get_characters(self):
        characters = []
        characters.append(self.character_1)
        characters.append(self.character_2)
        characters.append(self.character_3)
        
        return characters 
    
def create_player(sender, instance, created, **kwargs):
    if created:
        player = PlayerProfile.objects.create(user=instance)
        player.username = player.user.username
        player.save()
        
post_save.connect(create_player, sender=User)

sao_arena/arena/forms.py
from models import PlayerProfile
from django import forms
from django.contrib.auth.models import User


class PlayerProfileForm(forms.ModelForm):
    
    class Meta:
        model = PlayerProfile
        fields = ('avatar', 'character_1', 'character_2', 'character_3', )

    def UpdateCharacters(self, character_1, character_2, character_3):
        self.fields['character_1'].initial = character_1
        self.fields['character_2'].initial = character_2
        self.fields['character_3'].initial = character_3
        
    def validate(self, characters):
        "Check if value consists only of valid emails."

        # Use the parent's handling of required fields, etc.
        super(MultiEmailField, self).validate(value)
        
        character_1 = characters[0]
        character_2 = characters[1]
        character_3 = characters[3]
        
        if character_1 == character_2:
            raise forms.ValidationError("Cannot use more than one instance of a character")
        if character_1 == character_3:
            raise forms.ValidationError("Cannot use more than one instance of a character")
        if character_2 == character_3:
            raise forms.ValidationError("Cannot use more than one instance of a character")
        
    def clean_character1(self):
        data = self.cleaned_data['character_1']
        if character_1 == character_2:
            raise forms.ValidationError("Cannot use more than one instance of a character")
        if character_1 == character_3:
            raise forms.ValidationError("Cannot use more than one instance of a character")
        
        return data
    
    def clean_character2(self):
        data = self.cleaned_data['character_1']
        if character_2 == character_1:
            raise forms.ValidationError("Cannot use more than one instance of a character")
        if character_2 == character_3:
            raise forms.ValidationError("Cannot use more than one instance of a character")
        
        return data
    
    def clean_character3(self):
        data = self.cleaned_data['character_1']
        if character_3 == character_1:
            raise forms.ValidationError("Cannot use more than one instance of a character")
        if character_3 == character_2:
            raise forms.ValidationError("Cannot use more than one instance of a character")
        
        return data
        
        
        
class PlayerProfileUserForm(forms.ModelForm):
    
    class Meta:
        model = User
        fields = ('first_name', 'last_name')
        
    
    

sao_arena/arena/templates/PlayerProfile.html
{% extends 'base.html'%}
{% load i18n %}
{% load crispy_forms_tags %}

{% block jumbotron %}
<div class="row" style="padding-left: 10px;">
    <div class="col-md-6">
        <h1>{{user.username}}</h1>
    </div>
</div>
<div class="row" style="padding-left: 10px;">
    <div class="col-md-3">
        <img src="media/{{player.avatar}}/" style="padding-left: 10px; max-width: 200px; min-width: 300px; max-height: 300px; min-height: 300px;"/> 
    </div>
    <div class="col-md-4">
        <div class="well">
            <div class="row">
                <div class="col-sm-4">
                    <h4>Username: </h4>
                    <h4>Level: </h4>
                    <h4>Wins: </h4>
                    <h4>Defeats: </h4>
                    <h4>Win-Streak: </h4>
                </div>
                <div class="col-sm-6 col-sm-offset-1">
                    <h4>{{user.username}}</h4>
                    <h4>{{player.level}}</h4>
                    <h4>{{player.wins}}</h4>
                    <h4>{{player.defeats}}</h4>
                    <h4>{{player.winstreak}}</h4>
                </div>
            </div>
        </div>
<!--        <div class="well">
            <div class="row">
                <div class="col-sm-4">
                    <h4>First Name: </h4>
                    <h4>Last Name: </h4>
                    <h4>Email: </h4>

                </div>
                <div class="col-sm-6 col-sm-offset-1">
                    <h4>{{user.first_name}}</h4>
                    <h4>{{user.last_name}}</h4>
                    <h4>{{user.email}}</h4>

                </div>
            </div>
        </div> -->
    </div>
    <div class="col-md-4">
        <h3>Current Characters</h3>
        <div class="row">
            {%for character in characters %}
            <div class="col-sm-3">
               <img src="/media/{{media}}{{character.image}}" style="max-width: 100px; min-width: 100px; max-height: 100px; min-height: 100px;"/>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}


{% block content %}
{% if editing %}
<!--<h3>{{post}}</h3> -->
<div class="panel panel-info" style="padding-left: 10px;">
    <div class="panel panel-heading">
        <h2>Edit Profile Information</h2>
    </div>
    <div class="panel panel-body">
        <!--<h3>Personal Info</h3>
        <div class="well">
            <form method="post" action="profile">
                {% csrf_token %}
                {{ user_form|crispy }}
                <input class="btn btn-block" name="submit_changes" type="submit" value="Submit Changes"/>
            </form>
        </div>
        -->
        <div class="well">
            <img src="media/{{player.avatar}}/" style="max-width: 100px; min-width: 100px; max-height: 100px; min-height: 100px;"/>
            <form method="post" action="profile">
                {% csrf_token %}
                {{ player_form|crispy }}
                <input class="btn btn-block" name="submit_img" type="submit" value="Submit"/>
            </form>
            <form method="get" action="profile" style="padding-top: 10px;">
             {% csrf_token %}
            <input class="btn btn-block" name="submit_cancel" type="submit" value="Cancel Edit"/>
        </form>
        </div>

    </div>
</div>
{% else %}
<div class="row" style="padding-left: 10px;">
    <div class="col-xs-12">
        <form method="post" action="profile">
             {% csrf_token %}
            <input class="btn btn-block" name="submit_edit" type="submit" value="Edit Profile"/>
        </form>
    </div>
</div>

{% endif %}


{% endblock %}

sao_arena/arena/templates/characters.html
{% extends 'base.html' %}

{% block jumbotron %}
    <div class="jumbotron">
        <div class="container">
            <h1>SAO Arena Characters</h1>
            <p>a list of all characters</p>
        </div>
    </div>
{% endblock %}

{% block content %}

{% for character in characters %}

<div class="row">
    <div class="panel panel-default">
      <div class="panel-heading"><a href="/game-manual/characters/{{character.slug}}"><h2>{{ character.name }}</h2></a></div>
      <div class="panel-body">
        <div class="thumbnail col-md-2">
            <a href="/game-manual/characters/{{character.slug}}"><img src="/media/{{ character.image }}" style="max-height: 100px; max-width: 100px;"/></a>
        </div>
        <div class="container col-md-10">
            <p>{{ character.description }}</p>
        </div>
      </div>
    </div>
</div>

{% endfor %}

{% endblock %}

sao_arena/arena/templates/characterskills.html
{% extends 'base.html' %}

{% block heading %}
    <style type="text/css">
        
        img.thumbnail {
            max-height: 50%;
            max-width: 50%;
}
        }
        
        .case{
            background-color: black;
        }
        
        
    </style>
    
{% endblock %}

{% block jumbotron %}
    
    <h1>{{ character.name }}</h1>
    <div class="row">
        <div class="col-md-2">
            <img src="/media/{{character.image}}" style="max-width 200px; max-height: 200px;"/>
        </div>
        <div class="col-md-10">
            <p>{{ character.description }}</p>
        </div>
    </div>

    
{% endblock %}


{% block content %}


<div class="panel">
    <div class="panel-head">
        <h2>Skills</h2>
    </div>
    
    <div class="panel-body case">    
        <div class="well">
            <div class="row"> 
                {% for skill in skill_set %}
                    <div class="col-md-6">
                        <div class="panel" style="min-height: 600px">
                            <div class="panel-heading">
                                <p style="font-size: large; font-style: oblique;">{{ skill.name }}</p>
                                <img class="thumbnail" src="/media/{{skill.image}}" style="max-width 200px; max-height: 200px;">
                                <div class="row">
                                    <div class="col-md-3">
                                        <p>Energy Cost: </p>
                                    </div>
                                    <div class="col-sm-4">
                                    {% for energy in skill.energy.all%}
                                        {% if energy.amount == 2 %}
                                                {% if 'Green' in energy.color %}
                                                    <div class="thumbnail" style="background-color: green; min-width: 20px; min-height: 20px;
                                                    max-height: 20px; max-width: 20px; display: inline-block"></div>
                                                    <div class="thumbnail" style="background-color: green; min-width: 20px; min-height: 20px;
                                                    max-height: 20px; max-width: 20px; display: inline-block"></div>
                                                {%endif%}
                                                {% if 'Red' in energy.color %}
                                                    <div class="thumbnail" style="background-color: red; min-width: 20px; min-height: 20px;
                                                    max-height: 20px; max-width: 20px; display: inline-block"></div>
                                                    <div class="thumbnail" style="background-color: red; min-width: 20px; min-height: 20px;
                                                    max-height: 20px; max-width: 20px; display: inline-block"></div>
                                                {%endif%}
                                                {% if 'Blue' in energy.color %}
                                                    <div class="thumbnail" style="background-color: blue; min-width: 20px; min-height: 20px;
                                                    max-height: 20px; max-width: 20px; display: inline-block"></div>
                                                    <div class="thumbnail" style="background-color: blue; min-width: 20px; min-height: 20px;
                                                    max-height: 20px; max-width: 20px; display: inline-block"></div>
                                                {%endif%}
                                                {% if 'White' in energy.color %}
                                                    <div class="thumbnail" style="background-color: white; min-width: 20px; min-height: 20px;
                                                    max-height: 20px; max-width: 20px; display: inline-block"></div>
                                                    <div class="thumbnail" style="background-color: white; min-width: 20px; min-height: 20px;
                                                    max-height: 20px; max-width: 20px; display: inline-block"></div>
                                                {%endif%}
                                                {% if 'Black' in energy.color %}
                                                    <div class="thumbnail" style="background-color: black; min-width: 20px; min-height: 20px;
                                                    max-height: 20px; max-width: 20px; display: inline-block"></div>
                                                    <div class="thumbnail" style="background-color: black; min-width: 20px; min-height: 20px;
                                                    max-height: 20px; max-width: 20px; display: inline-block"></div>
                                                {%endif%}
                                        {% else %}
                                            <div class="thumbnail" style="background-color: {{ energy.color }}; min-width: 20px; min-height: 20px;
                                            max-height: 20px; max-width: 20px; display: inline-block"></div>
                                        {% endif %}
                                    {% endfor %}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-3">
                                        <p>Cooldown: </p>
                                    </div>
                                    <div class="col-sm-2">
                                        <p stlye="font-size: larger;">{{skill.cooldown}} turns</p>
                                    </div>
                                </div>
                            </div>
                            <div class="panel-body">
                                <div class="row">
                                    <p>{{ skill.description }}</p>
                                </div>
                                <div class="row">
                                    <div class=col-md-3">
                                        <p>Skill Types: </p>
                                    </div>
                                    <div class="col-md-9">
                                        <ul style="display: inline-block;">
                                            {% for skill_type in skill.skill_types.all %}
                                                {% if skill_type != skill.skill_types.last %}
                                                    <li style="display: inline-block;">{{ skill_type.name }}, </li>
                                                {% else %}
                                                    <li style="display: inline-block;">{{ skill_type.name }}</li>
                                                {% endif %}
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                    </div> 
                {% endfor %}
            </div>
        </div>
    </div>


</div>


{% endblock %}


{% block footing %}
{% endblock %}

sao_arena/arena/templates/home.html
{% extends 'base.html' %}

{% block jumbotron %}
    <div class="jumbotron">
        <div class="container">
            <h1>Welcome to the Sword Art Online Arena</h1>
            <p>Please choose a navigation option from the menu above</p>
        </div>
    </div>
{% endblock %}